apiVersion: v1
kind: Secret
metadata:
    name: restic-config-seerr-config
stringData:
    RESTIC_REPOSITORY: s3:https://fsn1.your-objectstorage.com/volsync-restic/seerr-config
    RESTIC_PASSWORD: ***REDACTED***
    AWS_ACCESS_KEY_ID: ***REDACTED***
    AWS_SECRET_ACCESS_KEY: ***REDACTED***
