apiVersion: v1
kind: Secret
metadata:
  name: restic-config-seerr-config
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:tPOOjFO+B/PMdHU1o8wQyQpI6kUxB58LPQZdyte7GxNWVkKhlRe8IjCX93lfYYDFQSdP+cvkfQgHpDoqY9uPwye+,iv:V4BPB79d9qSaSQY4/6ajaczb+wurjD2pWPieoDfzhIs=,tag:e0w34x36mNdGXotZukYXBw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:wJeMsIxPadB4u+xcAYk+OTy+efuODvM56w==,iv:AxRI6tf1z3XoGVG59rjlh6W43TmRK4PDPTmxmdqNF/s=,tag:NeyggV3ZmhqvUflTJ7lzaA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:b4F0iC5teLmiTIx7x5Nk/2gkLsE=,iv:N+yQf4lBi/VeQoL7tXzsjNSbigtlmcPM/DRtvPLfxMg=,tag:9de5qTepct+I3sOA8Zzo/g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:R/K3z6xThAh3SFZkf8qVHoEcoMeahSfsL7Tvn631Cz5bBKOlAg1rlw==,iv:r6971jVo23wUl+TlycXSZ6g9EkqLa7AXDE0wF5JSOaE=,tag:k28vdt1dxHhrjKzSy5L9yg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWGkzQzBhSVM2UE5LWDJy
        UURROXdoN0JHMTVhb0dZNExKbzdTb0dzU0hBCmJmY0owUTdzd0sybktmMmtOMk94
        MWxqRnV6cmVxMzZiUjJ6bCtEcFExbVEKLS0tIDZ5Qkhia2RLWUFFKzN4NXI0QlJB
        dFc5aVlsUlB6UTBwbnp0Z24vM2UyZDQKGJlgCYf13ZlrN1tcmVulDuoNkZaymzBk
        rAViIXwFPO5yI1Q03QypBBeJatNQcII43iSjxngMXtpy8om5qaNXcw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-22T07:42:31Z"
  mac: ENC[AES256_GCM,data:PIHZ2gQRpl8kLccHPBkuL2EPTVSksQZTLkBQ4YhzG0NUkoLUgpQp6HXeFDWn3lB4bN8A07cn/0TvuQPvMKSV0OK4/ZRndkNf6Ffm5dGKon49E+iFHF3e6HnK/VAxo4kPjm340xP58oZKy6kkELivkWQ6ja+KpJfwk+qsoTj1IOc=,iv:SOCFDl4P9fyNwJyfu6bmeCWaEaqvecezoglj2OC/maU=,tag:Y+TtGjvUX2EPKKkc4KtLpw==,type:str]
  version: 3.13.1
