---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arrs
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: ingress-nginx
      namespace: networking
    - name: csi-driver-smb
      namespace: kube-system
    - name: longhorn
      namespace: longhorn-system
    - name: pod-gateway-vpn
      namespace: networking
  values:
    controllers:
      radarr:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/radarr
              tag: 6.3.0@sha256:2b2c1c05eb3f648d2c80dfab9486147dd7bb0ad4d77fa972fc1c5de8f1da3738
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: Etc/UTC
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: arrs-secrets
                    key: RADARR_API_KEY
      sonarr:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/sonarr
              tag: 4.0.19@sha256:4b025354d338999e03bf6dbdadcdde94815d39d4a5aba5de3cdc86a56d7d6c51
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: Etc/UTC
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
              SONARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: arrs-secrets
                    key: SONARR_API_KEY
      bazarr:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/bazarr
              tag: 1.6.0@sha256:4c30dc0bb9a5d223075e7f5d12c77bd293c4b460f86d696dbe64763104c1e88c
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: Etc/UTC
              BAZARR__AUTH__METHOD: External
              BAZARR__AUTH__REQUIRED: DisabledForLocalAddresses
              BAZARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: arrs-secrets
                    key: SONARR_API_KEY
      prowlarr:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/prowlarr
              tag: 2.4.0@sha256:536036aeb2c740d1a660ccf143b58a8bd6222f09010258fdfc10a538af7bec78
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: Etc/UTC
              PROWLARR__AUTH__METHOD: External
              PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
      flaresolverr:
        containers:
          app:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
    service:
      radarr:
        controller: radarr
        ports:
          http:
            port: 7878
      sonarr:
        controller: sonarr
        ports:
          http:
            port: 8989
      bazarr:
        controller: bazarr
        ports:
          http:
            port: 6767
      prowlarr:
        controller: prowlarr
        ports:
          http:
            port: 9696
      flaresolverr:
        controller: flaresolverr
        ports:
          http:
            port: 8191
    ingress:
      main:
        className: "nginx"
        annotations:
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/auth-url: http://authelia.networking.svc.cluster.local/api/authz/auth-request
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
        hosts:
        - host: radarr.${SECRET_DOMAIN}
          paths:
          - path: /
            service:
              identifier: radarr
              port: http
        - host: sonarr.${SECRET_DOMAIN}
          paths:
          - path: /
            service:
              identifier: sonarr
              port: http
        - host: bazarr.${SECRET_DOMAIN}
          paths:
          - path: /
            service:
              identifier: bazarr
              port: http
        - host: prowlarr.${SECRET_DOMAIN}
          paths:
          - path: /
            service:
              identifier: prowlarr
              port: http
        tls:
        - secretName: radarr-tls
          hosts:
          - radarr.${SECRET_DOMAIN}
        - secretName: sonarr-tls
          hosts:
          - sonarr.${SECRET_DOMAIN}
        - secretName: bazarr-tls
          hosts:
          - bazarr.${SECRET_DOMAIN}
        - secretName: prowlarr-tls
          hosts:
          - prowlarr.${SECRET_DOMAIN}
    persistence:
      media:
        existingClaim: arrs-media
        advancedMounts:
          radarr:
            app:
              - path: "/movies"
                subPath: movies
          sonarr:
            app:
              - path: "/tv"
                subPath: tv
          bazarr:
            app:
              - path: "/movies"
                subPath: movies
              - path: "/tv"
                subPath: tv
      downloads:
        existingClaim: arrs-downloads
        advancedMounts:
          radarr:
            app:
              - path: "/downloads"
                subPath: ""
          sonarr:
            app:
              - path: "/downloads"
                subPath: ""
      radarr:
        existingClaim: radarr-data
        advancedMounts:
          radarr:
            app:
              - path: "/config"
      sonarr:
        existingClaim: sonarr-data
        advancedMounts:
          sonarr:
            app:
              - path: "/config"
      bazarr:
        existingClaim: bazarr-data
        advancedMounts:
          bazarr:
            app:
              - path: "/config"
      prowlarr:
        existingClaim: prowlarr-data
        advancedMounts:
          prowlarr:
            app:
              - path: "/config"
