---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.17.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: loki
  values:
    image:
      repository: grafana/promtail
      tag: 3.6.11@sha256:a761cb834cfaeee29745440d4884d6748f0a08d8f68928db1d707018c1dcfbe9
    serviceMonitor:
      enabled: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
