---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radicale
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: envoy-gateway
      namespace: networking
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: tomsquest/docker-radicale
              tag: 3.7.6.0@sha256:89fa44d02b134f0ac37cad809883327af8424499d913eec74f95085c458a93b7
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 5232
    route:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_GATEWAY}"
        hostnames:
        - "radicale.${SECRET_DOMAIN}"
        parentRefs:
        - name: external
          namespace: networking
        rules:
        - backendRefs:
          - identifier: main
            port: http
    persistence:
      config:
        type: configMap
        name: radicale-config
        globalMounts:
          - path: /config/config
            subPath: config.cfg
            readOnly: true
      auth:
        type: secret
        name: radicale-secrets
        globalMounts:
          - path: /config/users
            subPath: users
            readOnly: true
      data:
        existingClaim: radicale
        globalMounts:
          - path: /data
