---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  interval: 5m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-charts
        namespace: flux-system
  dependsOn:
    - name: envoy-gateway
      namespace: networking
  values:
    adminUser:
      create: true
      username: admin
      passwordHash: $2a$12$HQu99eymhRdEq9qZqqXqcewgY4HoRGPhxtlA5/l4E34p3lt1VNHz6
    # Exposed via httproute
    ingress:
      enabled: false
