apiVersion: v1
kind: Secret
metadata:
  name: headlamp-secrets
stringData:
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:3lqNM4Fc3wxGX/bjh1HS6FeuRvqRRHnOUw==,iv:5WJu+iP+Sa3oPSU9NFWzVfxK+pV5T0zlgl1D9DJWiLU=,tag:r5trMSynezPDyM+YEOTGiA==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:BAH0Ie4/+ECTfVQ9ltRihsDI/jMFqFgx04ozdrMIDMn/gpghgcHe5CbRN/BuqtgTKqmQcLLBd/zlc4yUkFDwmb2shYjEd6Jf,iv:IXmD0JHU0cwoOfJFC65avDsCUtV7hQ/zhBXRDKxr7h0=,tag:oNJrGruiS8qmb31U7EBhgA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/oIQ5wOygpcgKYPV9/rpP0iczBMtm3HBl524h2nC6kZuQRv0BUP8a8GeOpRTV/M4naruFlIu1lE4d3JZqbgRpmNvzoc8a9NR,iv:v2HLUKlR7m/O2x8dSBpnqa6Q1BkbWd9HEmNfc6nbzP4=,tag:VbFOjMrOcscLTYb+rTCayw==,type:str]
  OIDC_SCOPES: ENC[AES256_GCM,data:olOMwAwmM36rtztmbdfnOPijQlM=,iv:LXaCpjYiIVku91yWQodw7OHqGDptqmTaHmIDU9sztoQ=,tag:lhclcaFzfWiIxNUSWN2ztg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQXFGZXFXU2g5Tllic1VD
        dXFzQ3JRMitGV3FmTitlNnRSdEhsZm1ySmtvClRLdFEwUjBnM1NZNXZhV2ZhSXRK
        WmVSWHhsNEJiR2p3bTBOSG5TRDE0YW8KLS0tIG1NTmpKdlZMcDlqUFZrYjkrNVRp
        Z000cDNTZ3ArZ1kzanlUcDF0NG43alEK7ULLwkT6FnnowOSKYWoAZ8g2mDU4tndt
        fkkbxyPYxgCqG7vc4NkGnS0+/6c8rnIkKkVigYL5mOsZWnvOnVzOmg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T15:08:02Z"
  mac: ENC[AES256_GCM,data:zR9DsQXG9NbG7v63df5/f1vLVRTYqwHqfHZam7HD2DuTHvfpgTqfEJ1dc3Vus55qnz0drSTWW5wU1MYVgMWBopOk67WTWPNUIQTcilesNYgwhrbgLOxngfi8DomE+VRwQY/dRcDzJZbufHqipv0xDrxVdDCPwNYCm/JPlOb/xrk=,iv://MtiGbI7VjXZejvDKFjsXATKIaREv/jtRZW56UxaW4=,tag:rrHMS1SPOILmpnmzVfjB+g==,type:str]
  version: 3.8.1
