---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
  dependsOn:
    - name: envoy-gateway
      namespace: networking
  values:
    vpa:
      enabled: true
      recommender:
        resources:
          requests:
            cpu: 20m
            memory: 128Mi
          limits:
            memory: 256Mi
      admissionController:
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 128Mi
    controller:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi
    dashboard:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 128Mi
      # Exposed via httproute
      ingress:
        enabled: false
