---
apiVersion: v1
kind: Service
metadata:
  name: envoy-external
spec:
  type: ClusterIP
  selector:
    gateway.envoyproxy.io/owning-gateway-name: external
    gateway.envoyproxy.io/owning-gateway-namespace: networking
  ports:
  - name: https
    port: 443
    targetPort: 10443
    protocol: TCP
