---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopiur-app
  namespace: flux-system
spec:
  path: ./apps/kopiur
  targetNamespace: kopiur-system
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kopiur
      namespace: kopiur-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopiur-repository
  namespace: flux-system
spec:
  path: ./apps/kopiur/repository
  targetNamespace: kopiur-system
  interval: 10m
  prune: true
  dependsOn:
    - name: kopiur-app
  sourceRef:
    kind: GitRepository
    name: flux-system
