---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia-postgresql
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
    - name: longhorn
      namespace: longhorn-system
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
    controllers:
      primary:
        type: statefulset
        containers:
          postgresql:
            image:
              repository: public.ecr.aws/docker/library/postgres
              tag: 18.6@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
            env:
              POSTGRES_DB: authelia
              POSTGRES_USER: authelia
              POSTGRES_PASSWORD: ${SECRET_AUTHELIA_DB_PASSWORD}
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 750m
                memory: 768Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
          metrics:
            image:
              repository: quay.io/prometheuscommunity/postgres-exporter
              tag: v0.20.1@sha256:ac5ec343104fae0e2d84a27bb8d69b38430a11910c5382cad85d478d2bab713e
            env:
              DATA_SOURCE_URI: localhost:5432/postgres?sslmode=disable
              DATA_SOURCE_USER: authelia
              DATA_SOURCE_PASS: ${SECRET_AUTHELIA_DB_PASSWORD}
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 150m
                memory: 192Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
        initContainers:
          init-postgres-permissions:
            image:
              repository: alpine
              tag: 3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
            command: 
            - /bin/sh
            - -c
            - |
              chown -R 999:999 $PGDATA
              chmod 700 $PGDATA
            env:
              PGDATA: /var/lib/postgresql
            securityContext:
              runAsUser: 0
              runAsGroup: 0
          # # Init Container for Major PostgreSQL Upgrades, not needed permanently
          # pgautoupgrade:
          #   image:
          #     repository: pgautoupgrade/pgautoupgrade
          #     tag: 18-trixie
          #   env:
          #     PGAUTO_ONESHOT: "yes"
          #     POSTGRES_DB: authelia
          #     POSTGRES_PASSWORD: ${SECRET_AUTHELIA_DB_PASSWORD}
    service:
      primary:
        controller: primary
        ports:
          postgresql:
            port: 5432
      metrics:
        controller: primary
        ports:
          metrics:
            port: 9187
    persistence:
      data:
        existingClaim: authelia-postgresql-data
        globalMounts:
        - path: /var/lib/postgresql
          subPath: data
    serviceMonitor:
      main:
        enabled: true
        serviceName: authelia-postgresql-metrics
        endpoints:
          - port: metrics
