---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memos
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  dependsOn:
    - name: envoy-gateway
      namespace: networking
    - name: longhorn
      namespace: longhorn-system
    - name: memos-postgresql
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/usememos/memos
              tag: 0.30.0@sha256:71a5b4738d1bed96e92112004054f0888e92791b64eb78afd79077c96e6f9327
            env:
              MEMOS_PORT: "5230"
              MEMOS_DRIVER: postgres
              MEMOS_DSN: postgresql://memos:${SECRET_MEMOS_DB_PASSWORD}@memos-postgresql-primary:5432/memos?sslmode=disable
              MEMOS_PUBLIC: false
              MEMOS_PASSWORD_AUTH: false
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 5230
    route:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_GATEWAY}"
        hostnames:
          - "memos.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: networking
        rules:
          - backendRefs:
              - identifier: main
                port: http
