apiVersion: v1
kind: Secret
metadata:
    name: longhorn-system-secrets
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0lgNWxX7s7c=,iv:MCvFfbi5T4cax4qpjoFwTTIoGxftY7Rd3dS62pPsIWs=,tag:U292aN+pstcduqWQKKY2Kg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vn8VLF6RDrUjNlJHf8FTWSmZRycbmQzklk70+3E9B6G7H7xPLnoS7A==,iv:/EOTHi0dNVR62ZNK1ky+FZ9HYsojfdZBOFS0kvpcEps=,tag:1i0I4aRqKdiyaJ+ugDLYFw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:TDLu+TXZIQud1XXUy3ePsOpmXy80BstLMHkXmFE=,iv:nZNIgxHLToOZn7AWGUTxDo+juWh/HoN56SNfRzxbQ/A=,tag:/xjdsGcAlFBe2CGh1BZe8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UWQyRlpBUnhVdmx4ZWtJ
            QVhpQjZqQlpnWHVDak1uRzRrTzBPQVZaaEh3CjdtQW9SdG9LcGxuR2JScHFUd0Z1
            NFVjMVMwYnl2SHowR3FxYzVLcXNwM3MKLS0tIHNDU1l5WFhLZmFrRk05bVJHTXlQ
            OXV5NUJIeEZTWW9iWGNtM2ZEN05tUWcKb7sY2AW6+9Js0H/v7TJLa1C7ox7Lko/x
            DCwgNdC9Rk1alhpPuOMXyZzmPudsjbiiL0KdO5MmOYf1X51YeQ8hGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T13:43:27Z"
    mac: ENC[AES256_GCM,data:9KEACREgIBXsSwl1vU2DEQknQdn75QaDPEXJ75YqadW/Bgt6UHOGURk5ChOP8I+CGxNq+f4MBxZnu2igV/8Otmx9POtcPwmEuUrpqQDkl/9P7QmmN6PXoa3qaU0R6y13slEApUmJSs4A0urR+ZwLpPWgoJ6gsVqPLTsaMnXHFpg=,iv:YKZtF+GIi9M5dyzJMyURNuZyK3LIiKnwyYskLjRlgQw=,tag:tXRsthxrq5lZJ70zPkIVTA==,type:str]
    version: 3.13.1
