---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myfinnest-data
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: myfinnest-data
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: myfinnest-data
spec:
  repository:
    kind: ClusterRepository
    name: primary
  credentialProjection:
    enabled: true
  sources:
  - pvc:
      name: myfinnest-data
  retention:
    keepDaily: 7
    keepWeekly: 1
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: myfinnest-data
spec:
  policyRef:
    name: myfinnest-data
  schedule:
    cron: "0 6 * * *"
    runOnCreate: false
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: myfinnest-data
spec:
  repository:
    kind: ClusterRepository
    name: primary
  source:
    fromPolicy:
      name: myfinnest-data
  target:
    populator: {}
  credentialProjection:
    enabled: true
  mover:
    privilegedMode: true
  policy:
    onMissingSnapshot: Continue
