apiVersion: v1
kind: Secret
metadata:
  name: myfinnest
stringData:
  SESSION_SECRET: ENC[AES256_GCM,data:qSZgMlAKN7jytTee9wevsbyKt4v8EB4YcTkOjEdpqS8C9gC5g4rMRHEG/qCng2c9H26LuaCHQy8kGLl2lSj7tg==,iv:8eWq7vN/WHeouf+A1OKEQsiuVZ47+U3zLfekinGId+4=,tag:TVqGrT7Gy0L8lWBlhwZu0A==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:V7yudMU9FWWl2uUhEbArzN0xHkKVPVxtsGy7nLd4w3bTh0LNqtuVUpSwAvE9c5XdcxxZ7o1bKVO1WOD/YMQUI/f4k8LHAcWj,iv:YydO5QA8UuevX3Tbi/TTS/NVvc4AAnDVvKlGqgbWh9U=,tag:+yxVesJI3pGpZIepPJO7yg==,type:str]
  SYNC_API_TOKEN: ENC[AES256_GCM,data:wn6GdXNkhnaK6B1VRVxGIN/j4ZJDhglns6uJ2ImQFhZFpGCEIsVHxO4V7Hp7nHAeDh+E034JyNksmFuICTu+YA==,iv:Yu1paMehSH5qzKi7gLDbEKFF021lQBbZd/yUnTHoloA=,tag:nGEcRf5gFevvXPrTLo4/QQ==,type:str]
  CREDENTIALS_PUBLIC_KEY: ENC[AES256_GCM,data:fsdmiKA0FJa8BMlwqRWfnDR3VX1kbCowhLJjuoDzkJCPH5TLuJUhv3m+dTE=,iv:khNtUuHwCjs365tgJkyGGLnLp3B9GYJNdJdkv+qhack=,tag:y4TCfiyQzJKtPHTHzR8VKg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROWtvWXlmd1BJdWxKelAv
        MHk4bFQvS3dSUjhkY0xFeTBGUjdLQUltZkZnCkZQUVdoTTl5VXR6R1Awak1OZVk1
        RlNRbnFNd0k5TlQ4cWpXNmY0T2JDckEKLS0tIFl6RWpFakZ0OGh4N2Rnc01PNUpj
        NWIxYjZHVjd2Q1NEbGNpUXppUlJxUnMKr1vkqOi4Wzh210Exe5Eo8eBKYf67JuAw
        cgE8Y1+Ev0N4DHT2BQRvkBUI66bqH3jRRG4FMEg7y4pzQ3zdxBQ2ig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T18:13:42Z"
  mac: ENC[AES256_GCM,data:h9OJph4KVinnCUppOyExb/FjCH252eDg4cks+iyMaNLDfXYfUcz9TaQHDPiyiXWXUl9F31Jk0I7dtu+gw8BiwerfAnJIufgdhTKJAAFYEhGJhC1Uf7ijun11/WkojiMEWuzunfojtclw/Yllk1ktcha01TSM4M4/ccDGhl9XKIs=,iv:Q6+aVa+Gy0lHadPJ2nLjC1BBnyWNxEa2VprpwP7ITk8=,tag:AAn4ej/UMmaqKWFuN3AX1w==,type:str]
  version: 3.13.1
