apiVersion: v1
kind: Secret
metadata:
  name: myfinnest-sync-worker
stringData:
  SYNC_API_TOKEN: ENC[AES256_GCM,data:1UsS5yhL0aXorAWyoZrxaFHkN71OgQbJhNDEf4qWVMlIggCCd2K+FiSnzuHccWeUJGn4fq1pPXCMdKmSawfVfA==,iv:ZbwQaRsjREkDpeDC/taUcisL499NHa6aMY1tBZy2Gus=,tag:SvaCRU1HfrWELDZOmBUO7A==,type:str]
  CREDENTIALS_PRIVATE_KEY: ENC[AES256_GCM,data:S4s0qoMWol07snhSJXSG0Ale4Oufg4cYravEN3R2JthJUep/uHvz+C8Qabs=,iv:UE7Z0RnC6vXj15YrDiGN1/cQ3Xk1vQLtj2zoKFEQwQ8=,tag:yEX2+Y89CtySCX6hVMUAFA==,type:str]
  FINTS_PRODUCT_ID: ENC[AES256_GCM,data:GnroibvWN6B8jL55q85kwcNL09hlrbzXIw==,iv:zeq+iVl0yb4vMBHI5ZY2omysag7P+FVkHKNwhglHFkg=,tag:Bju7IxnOwhisf4p4ypwN3w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ2FSbmNRTkZ1aGpoeHVs
        NHlXbzR1OGRvZW83REJMKzMxM1pTSGV2cEhvCjRsUHZmRGZEa3NVNThFQ2NGY3dh
        V1FMa2J2YmlCZ1BtcU5uWC9ZNGpXSWsKLS0tIGJuMDVvSUNaT2pGekwwRFBQcEdS
        VWdGYmx0YzQ0cnZtck5ITy9Tck9pTG8KUfXAS0SHKWcZSA1cxTRoXpVUDxyQqrKz
        rjwQvuVMJS5IBAoEq7ngIufGX6VK0QsuuKIvpwWsu9ExOiByBobo5A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T18:13:42Z"
  mac: ENC[AES256_GCM,data:Y+sIgNM29R8vHWK/dk5VxEzTzZGpCS+GY52EehZ1zPxYsTmIMJQ1EMA71vV48910uTu1y2P0ErSBl5T/uFOPoIMXaSGGq1QJPDwqd5XKabNTsUWjDM/bVyh2O89IL3o9Sfm1U0HhnpYIblgYqbgVql1nPf1r/XwlIBiUKjDKcqI=,iv:+kH45hSKZIIVFbNn7T1dpWqFjRAoP3cXs/O5+hoMA+s=,tag:Bk2vjHXFUdQuTBTzBgPVAg==,type:str]
  version: 3.13.1
