---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: csi-driver-smb
      namespace: kube-system
    - name: envoy-gateway
      namespace: networking
    - name: longhorn
      namespace: longhorn-system
    - name: immich-redis
    - name: immich-postgresql
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v3.1.0@sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb
            env:
              DB_HOSTNAME: immich-postgresql-primary
              DB_DATABASE_NAME: immich
              DB_USERNAME: immich
              DB_PASSWORD: "${SECRET_IMMICH_DB_PASSWORD}"
              REDIS_HOSTNAME: immich-redis-master
              IMMICH_LOG_LEVEL: warn
              IMMICH_HELMET_FILE: "true"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      main:
        controller: main
        ports:
          http:
            port: 2283
    route:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_GATEWAY}"
        hostnames:
        - "immich.${SECRET_DOMAIN}"
        parentRefs:
        - name: external
          namespace: networking
        rules:
        - backendRefs:
          - identifier: main
            port: http
    persistence:
      data:
        existingClaim: immich
        globalMounts:
          - path: /usr/src/app/upload
