---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: enix-charts
  namespace: flux-system
spec:
  type: oci
  interval: 30m
  url: oci://quay.io/enix/charts
  timeout: 2m
