---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: myfinnest-charts
  namespace: flux-system
spec:
  type: oci
  interval: 30m
  url: oci://ghcr.io/pumba98/myfinnest/charts
  timeout: 2m
  secretRef:
    name: regcred
