---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
data:
  garage.toml: |
    data_dir     = "/var/lib/garage/store/data"
    metadata_dir = "/var/lib/garage/meta"

    db_engine = "sqlite"

    metadata_auto_snapshot_interval = "6h"

    replication_factor = 1

    rpc_bind_addr = "[::]:3901"

    [s3_api]
    api_bind_addr = "[::]:3900"
    s3_region = "us-east-1"

    [admin]
    api_bind_addr = "[::]:3903"
