apiVersion: v1
kind: Secret
metadata:
  name: garage-secrets
stringData:
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:57PJfGzboO2/5PqZxFPIrQuJCr9JzbDmPJ6BJ3k1hhgRurbX2DJqUt0ZhzHrloIy9UtQLkgneJlT4aUW+CKIZw==,iv:j801U49bvCS4SlRarZRR8yupnxeHQoc06OJggwZFBCU=,tag:RAgm4/TclPbihI05NrdXvw==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:iOrSnHFXsYG3d701aSeNUSGVFQVlmZ37jdijyDW4fQNo/f1yox80zKXo8xI=,iv:IXshkTzwaM8ul4pmc+rLCJqD9lCnud5akZtDg+F6AGs=,tag:12REM5Bes7sd8DdcVGuBsA==,type:str]
  GARAGE_DEFAULT_ACCESS_KEY: ENC[AES256_GCM,data:hsKbDLUaSI4=,iv:xmOaZWYRDtxHMw0n/PJc3tQWCl6pXpAptaU1ek004bs=,tag:WoP8UGaqbv+MQBx/Izq7XA==,type:str]
  GARAGE_DEFAULT_SECRET_KEY: ENC[AES256_GCM,data:RGzv5Tz2KlitlcdL0ZlE5VT61B6K3ftgAC3cYgp4hnKm9s/gn07k6g==,iv:HgRTXDXIfYkBI3fEDPI3RNLg9zIZ0kitbdr32m2JQmA=,tag:d9VsWPSw5Mux7YjE5sJbog==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdHRPZDJrMmtjS0p5TUFq
        dSt2TXhNbVNtTSt4YnQ2MkJwZEZIcnRvb3lBCnF1MW5sd05qeFh6WlR2dkE0MWo4
        alJUVVlFUFhmcjZObTFvUzF4KzJ4bTAKLS0tIFJ0K0JOVlQ0c1pKbks3ZUJ6dWNK
        RGVxemttRjZEWjFwREZ2Mms4WUs2bnMKlBoaBo0dQjF1hKn317Xws0VdsTfaSI9i
        vOhe+h7ZXlF2SU45UazUaotVNdP0lq5bjjzVyClmwbM9haMJPxEDbA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-17T21:53:00Z"
  mac: ENC[AES256_GCM,data:G+l8ozBQ6ZjTFtXUZGBDm3nkz4dZVcryWwwW9PK0FsoLuV+qPEMpWVw7TbltKfaGjvWgHSQPzkRktOcgbJEvD3g+chcwF06XS3+zRg6zmc7jNFkMfZ42BCbP19sDjcJX5Pbhp7ZKwNWgehPbrXyEQHSqgKuhW9O44tSUy11ZWsk=,iv:yt9BpwbmEK8MfehnJR1e4d1KrlaZ5oBT+Xvnx02Hjfg=,tag:btb0V+403qGvz9UHlUHN1g==,type:str]
  version: 3.13.1
