---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  dependsOn:
    - name: envoy-gateway
      namespace: networking
    - name: longhorn
      namespace: longhorn-system
    - name: linkwarden-postgresql
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/linkwarden/linkwarden
              tag: v2.16.1@sha256:6902e62a6d68e1906045310dbf9b2df7f3d784a7b2e9d0f02c23666023791634
            env:
              NEXTAUTH_URL: https://linkwarden.${SECRET_DOMAIN}/api/v1/auth
              DATABASE_URL: "postgres://linkwarden:${SECRET_LINKWARDEN_DB_PASSWORD}@linkwarden-postgresql-primary:5432/linkwarden"
              NEXT_PUBLIC_DISABLE_REGISTRATION: true
              NEXT_PUBLIC_CREDENTIALS_ENABLED: false
              NEXT_PUBLIC_AUTHELIA_ENABLED: true
              AUTHELIA_WELLKNOWN_URL: https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration
            envFrom:
              - secretRef:
                  name: linkwarden
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
    route:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_GATEWAY}"
        hostnames:
          - "linkwarden.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: networking
          - name: external
            namespace: networking
        rules:
          - backendRefs:
              - identifier: main
                port: http
    persistence:
      data:
        existingClaim: linkwarden-data
        globalMounts:
        - path: /data/data
