---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bind9
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  dependsOn:
    - name: metallb
      namespace: metallb-system
    - name: longhorn
      namespace: longhorn-system
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 101
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ubuntu/bind9
              tag: 9.20-26.04_stable@sha256:05ddc36f87b0fb6eb38e45125da419d557fb164412ffcce2a7f51a1b20049486
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
        initContainers:
          create-zone:
            image:
              repository: alpine
              tag: 3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
            command: 
            - /bin/sh
            - -c
            - |
              cp -n /tmp/*.zone /var/lib/bind/ && chown 101:101 /var/lib/bind/*.zone
    service:
      main:
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${LB_IP_BIND_SVC}"
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
    persistence:
      config:
        type: secret
        name: bind9-secrets
        globalMounts:
          - path: /etc/bind/named.conf
            subPath: named-${CLUSTER_BIND9_ROLE}.conf
            readOnly: true
          - path: /etc/bind/tsig.keys
            subPath: tsig.keys
            readOnly: true
          - path: /tmp/domain.zone
            subPath: domain.zone
            readOnly: true
          - path: /tmp/domain2.zone
            subPath: domain2.zone
            readOnly: true
      data:
        existingClaim: bind9-data
        globalMounts:
          - path: /var/lib/bind
      cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Mi
        globalMounts:
          - path: /var/cache/bind
