---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../namespaces.yaml
- ../alloy.yaml
- ../bind9.yaml
- ../blocky.yaml
- ../certificate-exporter.yaml
- ../flux-system.yaml
- ../kopiur.yaml
- ../kube-prometheus-stack.yaml
- ../loki.yaml
- ../longhorn.yaml
- ../metallb.yaml
- ../metrics-server.yaml
- ../reloader.yaml
- ../snapshot-controller.yaml
- ../tuppr.yaml

patches:
- path: bind9.yaml
- path: blocky.yaml
- path: kube-prometheus-stack.yaml
- path: longhorn.yaml
