apiVersion: v1
kind: Secret
metadata:
    name: kopia-cluster-creds
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VROyibWA+l44nl8lUyrfQp3z7nQ=,iv:UJcWUBvhAeV2eLlz0yf/79Bs0TgdlUKK141ob/qWIZk=,tag:o4zqRpEgAozFtA5+lngocQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dPCG2HKWyYPbcnJMTHrfXgBSXbAXLBgdgiwdWFX0GI6bS2wesKHXvw==,iv:46jZhRRUOic7zSYIemEthJMKgcskzfXBtQrLMaBUXlM=,tag:nn9lgdcI9Y/SpeZydkX0UA==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:46QAWOAO7rz1W9nPrdqjVg3Qk2vl1XW/7ghYsNEcaUU=,iv:h0ePpG3qp0ITcIqooaaZevLnKjrn6C9uHPOOwumQphU=,tag:bViUwx7zhKz0XJNlZkAReQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbVVvMTNGTCtwaTRUL21w
            UUlRd3J2cVNkV2ZWWko4Zm43NFhBR2ZKREY0Cmh2aTJHbTNNYTdyOE5BZElMd054
            VkZFMyt6and4ckVWc0hnRUpPcXJkN1UKLS0tIEtneTJra3RCYXd2ZnVmZ0xjbTBQ
            N0ZwZ2Npd1ZNN2t6OXF6dEdDSVRKQ1kKt6717rkJMaAtZSvvf3+q/tYxvA+jXZ3W
            VHRHN3COYoZv8z2yWB5oWDv+xElXKKiIwkp7sFadeZ/vA1IHWBzs0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzqxk3z5anq53lz9g4rd7eatczfcd7vjszgggr47927mwe7hjfhq3tlad6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T19:18:14Z"
    mac: ENC[AES256_GCM,data:iCiBcc2Ka7w/UnoJ+MDQVE8uxXUOXBig4+EJH1TocxsjTm+ocIwduA9gjKyT7gltE5cFChLNa4bXcKsYKAG6K5GQJ6UaVlNLsn4Bp5lGG70fFbiJzzsBm54pBykasTC0Nhh/O6G4++jauAB+kDmQiFJHXFixao17TS4AxANLzMU=,iv:GDcgZNYBafXNiedin4oNNcLAp9vye8WQaMs0VzrZNwU=,tag:zf9OMG7eZxYR5mkakG6mYA==,type:str]
    version: 3.13.1
