---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  policy:
    waitForVolumeDetach: true
  healthChecks:
    - apiVersion: longhorn.io/v1beta2
      kind: Volume
      namespace: longhorn-system
      expr: status.robustness in ["healthy", "unknown"]
      timeout: 30m
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/talos
    version: v1.14.0
