---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jd2
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  dependsOn:
    - name: envoy-gateway
      namespace: networking
    - name: csi-driver-smb
      namespace: kube-system
    - name: longhorn
      namespace: longhorn-system
    - name: pod-gateway-vpn
      namespace: networking
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: jlesage/jdownloader-2
              tag: v26.09.1@sha256:bd6cd2fdc72818f30207e677b33cd7f1b425048c4e7132624e541e99f992be4c
              pullPolicy: IfNotPresent
            env:
              KEEP_APP_RUNNING: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      main:
        controller: main
        ports:
          http:
            port: 5800
    route:
      main:
        annotations:
          external-dns.kubernetes.io/target: "${SECRET_GATEWAY}"
        hostnames:
        - "jd2.${SECRET_DOMAIN}"
        parentRefs:
        - name: internal
          namespace: networking
        - name: external
          namespace: networking
        rules:
        - backendRefs:
          - identifier: main
            port: http
    persistence:
      config:
        existingClaim: jd2-config
        globalMounts:
          - path: "/config"
      output:
        existingClaim: jd2-output
        globalMounts:
          - path: "/output"
