originRequest:
  http2Origin: true
ingress:
- hostname: "auth.${SECRET_DOMAIN}"
  service: https://envoy-external.networking.svc.cluster.local:443
  originRequest:
    originServerName: "auth.${SECRET_DOMAIN}"
    noTLSVerify: true
- hostname: "*.${SECRET_DOMAIN}"
  service: https://envoy-external.networking.svc.cluster.local:443
  originRequest:
    originServerName: "${SECRET_GATEWAY}"
    noTLSVerify: true
- service: http_status:404
